name: Publish
permissions:
  contents: write

on:
  create:
    tags:
      - '*.*.*'  # Matches numerical version tags like 1.0.0, 2.1.3, etc.

jobs:

  create-release:
    uses: SilverPineSoftware/UUGithubActions/.github/workflows/uu_create_release.yml@main
    secrets:
      UU_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      